version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: farmin-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "@14vishnuVVA"
      MYSQL_DATABASE: farmin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p@14vishnuVVA"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-server:
    build: .
    container_name: farmin-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "@14vishnuVVA"
      DB_NAME: farmin
      JWT_SECRET: super_secret_jwt_sign_key_for_farmin_enterprise
      NODE_ENV: production
    depends_on:
      mysql-db:
        condition: service_healthy

volumes:
  mysql_data:
